paths:
  pdf_dir: "pdfs"
  cache_dir: ".raq_cache"
  crossref_email: null  # optional; some APIs accept mailto

indexing:
  page_split: "sliding"           # "page" | "sentence" | "sliding"
  window_chars: 600               # used when page_split == "sliding" (optimal for precision)
  overlap_chars: 80               # used when page_split == "sliding" (20% overlap)
  text_quality_check: true        # Enable text quality validation for PDFs
  min_readable_ratio: 0.5         # Minimum ratio of readable characters (0.0-1.0)

bm25:
  k1: 1.5                         # Term frequency saturation (tuned for sliding windows)
  b: 0.75                         # Document length normalization (tuned for shorter chunks)
  build_top_k: 300                # candidate pool from lexical stage (pre-rerank)
  pool_size: 200                  # candidates from lexical stage before fusion/rerank
  token_pattern: "[A-Za-z0-9]+"

prf:                              # RM3
  enabled: false
  fb_docs: 6
  fb_terms: 10
  alpha: 0.6

bonuses:
  proximity:
    enabled: true
    window: 24                    # Smaller window for sliding chunks (was 30)
    weight: 0.2
  ngram:
    enabled: true
    weight: 0.1
  patterns:
    enabled: true
    patterns: [" is a ", " we define ", " we propose ", " we argue ",
               " consists of ", " stakeholders include ", " method ", " methodology "]
    weight_per_hit: 0.05
    max_hits: 6

diversity:
  enabled: true
  per_doc_penalty: 0.3
  max_per_doc: 2
  mmr:
    enabled: true                 # Enable MMR for final diversification
    lambda: 0.7                   # Balance between relevance and diversity

rerank:
  heuristic:
    enabled: true                 # Enable lightweight heuristic reranker
    topn: 150                     # Candidates to rerank heuristically
    alpha: 0.6                    # Weight for coverage score
    beta: 0.3                     # Weight for proximity score
    gamma: 0.1                    # Weight for phrase boost
  semantic:
    enabled: true
    model: "sentence-transformers/all-MiniLM-L6-v2"
    topn: 80                      # Reduced for efficiency (was 120)
  final_top_k: 8                  # number of items to return/print

fusion:
  rrf:
    enabled: true                 # Enable Reciprocal Rank Fusion
    C: 75                         # RRF parameter (slightly higher for more runs)
    cap: 200                      # Max items per run to consider in fusion
  robust_query:
    enabled: true                 # Enable robust query variant run

citations:
  crossref: true
  openalex: true
  unpaywall: false
  unpaywall_email: null  # Required for Unpaywall API if enabled
  cache_seconds: 604800          # 7 days
  page_offset_from_crossref: true
  # future: try page offset from OpenAlex host venue pages if Crossref lacks 'page'

output:
  max_snippet_chars: 900
  pretty_json: true
  include_scores: true

performance:
  api_semaphore_size: 5      # Max concurrent API calls
  pdf_thread_workers: null   # None = auto (num_cores), or set manually
  deterministic: true        # Enable deterministic tie-breaking
  numpy_seed: 42             # Seed for numpy random operations